version: '2.4'
services:
  # piggymetrics
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - piggynet
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-config
    container_name: config
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      SW_SVC_NAME: config
      SW_URL: oap:11800
    networks:
      - piggynet
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  registry:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-registry
    container_name: registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      SW_SVC_NAME: registry
      SW_URL: oap:11800
    networks:
      - piggynet
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-gateway
    container_name: gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      SW_SVC_NAME: gateway
      SW_URL: oap:11800
    networks:
      - piggynet
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  auth-service:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-auth-service
    container_name: auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      SW_SVC_NAME: auth-service
      SW_URL: oap:11800
    networks:
      - piggynet
    ports:
      - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  auth-mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-mongodb
    container_name: auth-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      TZ: Asia/Shanghai
    networks:
      - piggynet
    ports:
      - 25000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  account-service:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-account-service
    container_name: account-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      SW_SVC_NAME: account-service
      SW_URL: oap:11800
    networks:
      - piggynet
    ports:
      - 6000:6000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  account-mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-mongodb
    container_name: account-mongodb
    restart: always
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      TZ: Asia/Shanghai
    networks:
      - piggynet
    ports:
      - 26000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  statistics-service:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-statistics-service
    container_name: statistics-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      SW_SVC_NAME: statistics-service
      SW_URL: oap:11800
    networks:
      - piggynet
    ports:
      - 7000:7000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  statistics-mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-mongodb
    container_name: statistics-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      TZ: Asia/Shanghai
    networks:
      - piggynet
    ports:
      - 27000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  notification-service:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-notification-service
    container_name: notification-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      SW_SVC_NAME: notification-service
      SW_URL: oap:11800
    networks:
      - piggynet
    ports:
      - 8000:8000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  notification-mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggymetrics-mongodb
    container_name: notification-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      TZ: Asia/Shanghai
    networks:
      - piggynet
    ports:
      - 28000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
        max-buffer-size: 4m

  # efk configurations
  elasticsearch:
    image: elasticsearch:6.8.4
    container_name: elasticsearch
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - piggynet
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  fluentd:
    image: fluentd
    container_name: fluentd
    networks:
      - piggynet
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    environment:
      - TZ=Asia/Shanghai

  kibana:
    image: kibana:6.8.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Shanghai
      - discovery.type=single-node
    networks:
      - piggynet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # skywalking
  oap:
    image: apache/skywalking-oap-server:6.5.0
    container_name: oap
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - piggynet
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      - TZ=Asia/Shanghai
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200

  ui:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/skywalking-rocketbot-ui
    container_name: ui
    depends_on:
      - oap
    restart: always
    networks:
      - piggynet
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Shanghai
      - SKYWALKING_URL=oap:12800
volumes:
  esdata:
    driver: local
networks:
  piggynet:
    driver: bridge