name: Gateway CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Build & Push Docker Image
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          name: shenmiu/piggymetrics-gateway:latest
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{secrets.Ali_USER}}
          password: ${{secrets.Ali_PWD}}
          workdir: ./gateway